### ISSUE TITLE
Bug in bulk write mongodb

### ISSUE THREAD

**Issue by Ilke-dev** [cve-search/CveXplore#252]
It seems that the downloader crashes with the following exception:
![image](https://github.com/cve-search/CveXplore/assets/105493024/05abd7fe-c0ad-46ec-bf0e-2e6944ba5b2e)

I've located where it crashes, and it seems that the following method "self.process_item" returns None values:
https://github.com/cve-search/CveXplore/blob/6020655316f82bac048bb76a58f108902d699cec/CveXplore/database/maintenance/Sources_process.py#L245

These None values are possibly generated because of this method: https://github.com/cve-search/CveXplore/blob/6020655316f82bac048bb76a58f108902d699cec/CveXplore/database/maintenance/Sources_process.py#L87

These None values are then passed into the "_db_bulk_writer" method which in turn crashes because a None value doesn't have the expected methods/attributes, see here:
https://github.com/cve-search/CveXplore/blob/6020655316f82bac048bb76a58f108902d699cec/CveXplore/database/maintenance/Sources_process.py#L248

It might be a good idea to filter out all the None values before passing the list into _db_bulk_writer like this:
```python
processed_items = [i for i in processed_items if i is not None]
```

**Comment by P-T-I** [comment]
Hey; I believe this to be already fixed in the master branch; could you verify?

**Comment by Ilke-dev** [comment]
i think the issue still remains if i read the code, the actual problem lies here: 
https://github.com/cve-search/CveXplore/blob/80ebd624f68d7505133811cb270895bcc7e15a25/CveXplore/core/database_maintenance/sources_process.py#L79

This method returns None values if the CVE is not to be processed because of deprecation and other reasons. 

You still need to plug this line to filter out the None values generated from the method above:
https://github.com/cve-search/CveXplore/blob/master/CveXplore/core/database_maintenance/sources_process.py#L240

**Comment by P-T-I** [comment]
It true that those functions could still return None; but in the _db_bulk_writer those 'None' values are removed from the batch variable before transmitting them to the database.

**Comment by Ilke-dev** [comment]
Do you mean this line?

https://github.com/cve-search/CveXplore/blob/master/CveXplore/core/database_maintenance/download_handler.py#L216

**Comment by P-T-I** [comment]
Yes; and 4 lines up

**Comment by Ilke-dev** [comment]
That should fix the issues i think. 
Let's close this issue then.

**Comment by odolezal** [comment]
I think that this issue still exist:

```
cvexplore --version             
0.3.20
```
When I run:
```
cvexplore database update
```
I got:
```python
2024-01-10 14:26:35,394 - CveXplore.database.maintenance.main_updater - INFO     - Starting Database update....
2024-01-10 14:26:35,403 - CveXplore.api.nvd_nist.nvd_nist_api - WARNING  - Could not find a NIST API Key in the '~/.cvexplore/.env' file; you could request one at: https://nvd.nist.gov/developers/request-an-api-key
2024-01-10 14:26:35,404 - CveXplore.database.maintenance.Sources_process - INFO     - CPE database update started
2024-01-10 14:26:35,404 - CveXplore.database.maintenance.Sources_process - INFO     - Starting download...
2024-01-10 14:26:36,072 - CveXplore.database.maintenance.Sources_process - INFO     - Preparing to download 690 CPE entries
Downloading and processing content:   0%|                                                                                                                                          | 0/690 [00:04<?, ?it/s]
Traceback (most recent call last):                                                                                                                                                                         
  File "/home/cve-search/.local/lib/python3.10/site-packages/pymongo/collection.py", line 566, in bulk_write
    request._add_to_bulk(blk)
AttributeError: 'NoneType' object has no attribute '_add_to_bulk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cve-search/.local/bin/cvexplore", line 8, in <module>
    sys.exit(main())
  File "/home/cve-search/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/cve-search/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/cve-search/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cve-search/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cve-search/.local/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/home/cve-search/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cve-search/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/cve-search/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cve-search/.local/lib/python3.10/site-packages/CveXplore/cli_cmds/db_cmds/commands.py", line 22, in update_cmd
    ctx.obj["data_source"].database.update()
  File "/home/cve-search/.local/lib/python3.10/site-packages/CveXplore/database/maintenance/main_updater.py", line 73, in update
    up.update()
  File "/home/cve-search/.local/lib/python3.10/site-packages/CveXplore/database/maintenance/Sources_process.py", line 269, in update
    self.process_downloads()
  File "/home/cve-search/.local/lib/python3.10/site-packages/CveXplore/database/maintenance/Sources_process.py", line 248, in process_downloads
    self._db_bulk_writer(processed_items)
  File "/home/cve-search/.local/lib/python3.10/site-packages/CveXplore/database/maintenance/DownloadHandler.py", line 173, in _db_bulk_writer
    self.database[self.feed_type.lower()].bulk_write(batch, ordered=False)
  File "/home/cve-search/.local/lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/cve-search/.local/lib/python3.10/site-packages/pymongo/collection.py", line 568, in bulk_write
    raise TypeError(f"{request!r} is not a valid request")
TypeError: None is not a valid request
```

**Comment by P-T-I** [comment]
@odolezal In 0.3.20; Yes. In current master it should be fixed
